import { Question, SubjectData, PracticeHistoryItem } from "./practice-types";

export const subjects: SubjectData[] = [
  {
    name: "Mathematics",
    topics: ["Algebra", "Calculus", "Geometry", "Statistics", "Trigonometry"],
  },
  {
    name: "Computer Science",
    topics: ["Data Structures", "Algorithms", "Programming", "Databases", "Operating Systems"],
  },
  {
    name: "English",
    topics: ["Grammar", "Vocabulary", "Reading Comprehension", "Writing", "Literature"],
  },
  {
    name: "Physics",
    topics: ["Mechanics", "Thermodynamics", "Electromagnetism", "Optics", "Quantum Physics"],
  },
  {
    name: "Chemistry",
    topics: ["Organic Chemistry", "Inorganic Chemistry", "Physical Chemistry", "Biochemistry", "Analytical Chemistry"],
  },
];

export const questionBank: Question[] = [
  // Mathematics Questions
  {
    id: "math-1",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "easy",
    questionType: "mcq",
    questionText: "What is the value of x in the equation 2x + 5 = 13?",
    options: ["3", "4", "5", "6"],
    correctAnswer: 1,
    explanation: "Subtract 5 from both sides: 2x = 8. Then divide by 2: x = 4.",
    isBookmarked: false,
  },
  {
    id: "math-2",
    subject: "Mathematics",
    topic: "Calculus",
    difficulty: "medium",
    questionType: "mcq",
    questionText: "What is the derivative of f(x) = 3x² + 2x + 1?",
    options: ["6x + 2", "3x + 2", "6x + 1", "3x² + 2"],
    correctAnswer: 0,
    explanation: "Using the power rule: d/dx(3x²) = 6x, d/dx(2x) = 2, d/dx(1) = 0. So f'(x) = 6x + 2.",
    isBookmarked: false,
  },
  {
    id: "math-3",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "hard",
    questionType: "mcq",
    questionText: "What is the area of a circle with radius 7 cm? (Use π ≈ 22/7)",
    options: ["44 cm²", "154 cm²", "308 cm²", "49 cm²"],
    correctAnswer: 1,
    explanation: "Area = πr² = (22/7) × 7² = (22/7) × 49 = 22 × 7 = 154 cm².",
    isBookmarked: false,
  },
  {
    id: "math-4",
    subject: "Mathematics",
    topic: "Statistics",
    difficulty: "medium",
    questionType: "true-false",
    questionText: "The median is always equal to the mean in a normal distribution.",
    options: ["True", "False"],
    correctAnswer: 0,
    explanation: "In a perfectly normal distribution, the mean, median, and mode are all equal.",
    isBookmarked: false,
  },
  {
    id: "math-5",
    subject: "Mathematics",
    topic: "Trigonometry",
    difficulty: "easy",
    questionType: "mcq",
    questionText: "What is sin(90°)?",
    options: ["0", "1", "-1", "0.5"],
    correctAnswer: 1,
    explanation: "At 90 degrees, the sine function reaches its maximum value of 1.",
    isBookmarked: false,
  },

  // Computer Science Questions
  {
    id: "cs-1",
    subject: "Computer Science",
    topic: "Data Structures",
    difficulty: "easy",
    questionType: "mcq",
    questionText: "Which data structure operates on a Last-In, First-Out (LIFO) principle?",
    options: ["Queue", "Stack", "Linked List", "Tree"],
    correctAnswer: 1,
    explanation: "A Stack follows the LIFO principle where the last element added is the first one to be removed.",
    isBookmarked: false,
  },
  {
    id: "cs-2",
    subject: "Computer Science",
    topic: "Algorithms",
    difficulty: "medium",
    questionType: "mcq",
    questionText: "What is the time complexity of binary search in a sorted array?",
    options: ["O(n)", "O(log n)", "O(n²)", "O(1)"],
    correctAnswer: 1,
    explanation: "Binary search divides the search space in half with each comparison, resulting in O(log n) time complexity.",
    isBookmarked: false,
  },
  {
    id: "cs-3",
    subject: "Computer Science",
    topic: "Programming",
    difficulty: "hard",
    questionType: "mcq",
    questionText: "Which of the following is NOT a valid JavaScript data type?",
    options: ["Symbol", "Undefined", "Float", "BigInt"],
    correctAnswer: 2,
    explanation: "JavaScript has Number type which represents both integers and floating-point numbers. There is no separate 'Float' type.",
    isBookmarked: false,
  },
  {
    id: "cs-4",
    subject: "Computer Science",
    topic: "Databases",
    difficulty: "medium",
    questionType: "true-false",
    questionText: "SQL is a procedural programming language.",
    options: ["True", "False"],
    correctAnswer: 1,
    explanation: "SQL is a declarative language, not procedural. You specify what you want, not how to get it.",
    isBookmarked: false,
  },
  {
    id: "cs-5",
    subject: "Computer Science",
    topic: "Operating Systems",
    difficulty: "hard",
    questionType: "mcq",
    questionText: "Which scheduling algorithm is designed to minimize average waiting time?",
    options: ["First-Come, First-Served", "Round Robin", "Shortest Job First", "Priority Scheduling"],
    correctAnswer: 2,
    explanation: "Shortest Job First (SJF) scheduling minimizes average waiting time by executing the shortest jobs first.",
    isBookmarked: false,
  },

  // English Questions
  {
    id: "eng-1",
    subject: "English",
    topic: "Grammar",
    difficulty: "easy",
    questionType: "mcq",
    questionText: "Which sentence is grammatically correct?",
    options: ["She don't like coffee.", "She doesn't likes coffee.", "She doesn't like coffee.", "She don't likes coffee."],
    correctAnswer: 2,
    explanation: "The correct form is 'doesn't like' - third person singular uses 'doesn't' + base form of the verb.",
    isBookmarked: false,
  },
  {
    id: "eng-2",
    subject: "English",
    topic: "Vocabulary",
    difficulty: "medium",
    questionType: "mcq",
    questionText: "What is the meaning of 'ubiquitous'?",
    options: ["Rare", "Present everywhere", "Ancient", "Dangerous"],
    correctAnswer: 1,
    explanation: "Ubiquitous means seeming to be everywhere at the same time; omnipresent.",
    isBookmarked: false,
  },
  {
    id: "eng-3",
    subject: "English",
    topic: "Writing",
    difficulty: "hard",
    questionType: "mcq",
    questionText: "Which literary device uses 'like' or 'as' to make a comparison?",
    options: ["Metaphor", "Simile", "Personification", "Hyperbole"],
    correctAnswer: 1,
    explanation: "A simile explicitly uses 'like' or 'as' to compare two things, while a metaphor makes an implicit comparison.",
    isBookmarked: false,
  },
  {
    id: "eng-4",
    subject: "English",
    topic: "Literature",
    difficulty: "medium",
    questionType: "true-false",
    questionText: "William Shakespeare wrote 'Romeo and Juliet'.",
    options: ["True", "False"],
    correctAnswer: 0,
    explanation: "William Shakespeare is indeed the author of the famous tragedy 'Romeo and Juliet'.",
    isBookmarked: false,
  },
  {
    id: "eng-5",
    subject: "English",
    topic: "Reading Comprehension",
    difficulty: "easy",
    questionType: "mcq",
    questionText: "In the sentence 'The cat sat on the mat', what is the subject?",
    options: ["Cat", "Mat", "Sat", "The"],
    correctAnswer: 0,
    explanation: "The subject is 'the cat' - the entity performing the action of sitting.",
    isBookmarked: false,
  },

  // Physics Questions
  {
    id: "phy-1",
    subject: "Physics",
    topic: "Mechanics",
    difficulty: "easy",
    questionType: "mcq",
    questionText: "What is the SI unit of force?",
    options: ["Joule", "Watt", "Newton", "Pascal"],
    correctAnswer: 2,
    explanation: "The SI unit of force is the Newton (N), named after Sir Isaac Newton.",
    isBookmarked: false,
  },
  {
    id: "phy-2",
    subject: "Physics",
    topic: "Thermodynamics",
    difficulty: "medium",
    questionType: "mcq",
    questionText: "What is the first law of thermodynamics also known as?",
    options: ["Law of Entropy", "Law of Conservation of Energy", "Law of Heat Transfer", "Law of Absolute Zero"],
    correctAnswer: 1,
    explanation: "The first law of thermodynamics is essentially the law of conservation of energy applied to thermal systems.",
    isBookmarked: false,
  },
  {
    id: "phy-3",
    subject: "Physics",
    topic: "Electromagnetism",
    difficulty: "hard",
    questionType: "mcq",
    questionText: "What is the relationship between electric field (E) and potential (V)?",
    options: ["E = V/d", "E = V × d", "E = dV/dt", "E = V²"],
    correctAnswer: 0,
    explanation: "Electric field is the negative gradient of electric potential: E = -dV/dr, or in uniform fields E = V/d.",
    isBookmarked: false,
  },
  {
    id: "phy-4",
    subject: "Physics",
    topic: "Optics",
    difficulty: "medium",
    questionType: "true-false",
    questionText: "Light travels faster in water than in vacuum.",
    options: ["True", "False"],
    correctAnswer: 1,
    explanation: "Light travels slowest in dense media like water and fastest in vacuum (the speed of light in vacuum is the maximum).",
    isBookmarked: false,
  },
  {
    id: "phy-5",
    subject: "Physics",
    topic: "Quantum Physics",
    difficulty: "hard",
    questionType: "mcq",
    questionText: "Who proposed the wave-particle duality of light?",
    options: ["Newton", "Einstein", "de Broglie", "Bohr"],
    correctAnswer: 2,
    explanation: "Louis de Broglie proposed that all matter exhibits wave-particle duality, extending the concept beyond light.",
    isBookmarked: false,
  },

  // Chemistry Questions
  {
    id: "chem-1",
    subject: "Chemistry",
    topic: "Organic Chemistry",
    difficulty: "easy",
    questionType: "mcq",
    questionText: "What is the functional group in alcohols?",
    options: ["-COOH", "-OH", "-NH2", "-CHO"],
    correctAnswer: 1,
    explanation: "Alcohols contain the hydroxyl functional group (-OH) bonded to a carbon atom.",
    isBookmarked: false,
  },
  {
    id: "chem-2",
    subject: "Chemistry",
    topic: "Inorganic Chemistry",
    difficulty: "medium",
    questionType: "mcq",
    questionText: "What is the atomic number of Carbon?",
    options: ["6", "12", "14", "8"],
    correctAnswer: 0,
    explanation: "Carbon has an atomic number of 6, meaning it has 6 protons in its nucleus.",
    isBookmarked: false,
  },
  {
    id: "chem-3",
    subject: "Chemistry",
    topic: "Physical Chemistry",
    difficulty: "hard",
    questionType: "mcq",
    questionText: "What is the ideal gas equation?",
    options: ["PV = nRT", "PV = RT", "P = nRT/V", "V = nRT/P"],
    correctAnswer: 0,
    explanation: "The ideal gas law is PV = nRT, where P is pressure, V is volume, n is moles, R is the gas constant, and T is temperature.",
    isBookmarked: false,
  },
  {
    id: "chem-4",
    subject: "Chemistry",
    topic: "Biochemistry",
    difficulty: "medium",
    questionType: "true-false",
    questionText: "DNA is a protein.",
    options: ["True", "False"],
    correctAnswer: 1,
    explanation: "DNA is a nucleic acid, not a protein. Proteins are made of amino acids, while DNA is made of nucleotides.",
    isBookmarked: false,
  },
  {
    id: "chem-5",
    subject: "Chemistry",
    topic: "Analytical Chemistry",
    difficulty: "easy",
    questionType: "mcq",
    questionText: "What pH value indicates a neutral solution?",
    options: ["0", "7", "14", "1"],
    correctAnswer: 1,
    explanation: "A pH of 7 is neutral. Values below 7 are acidic, and values above 7 are basic.",
    isBookmarked: false,
  },
];

export const practiceHistory: PracticeHistoryItem[] = [
  {
    id: "hist-1",
    date: "2026-08-31T10:30:00",
    mode: "normal",
    subject: "Mathematics",
    score: "80%",
    timeTaken: "15:30",
    sessionId: "session-1",
  },
  {
    id: "hist-2",
    date: "2026-08-30T14:45:00",
    mode: "timed",
    subject: "Computer Science",
    score: "92%",
    timeTaken: "10:00",
    sessionId: "session-2",
  },
  {
    id: "hist-3",
    date: "2026-08-29T09:15:00",
    mode: "topic",
    subject: "English",
    score: "75%",
    timeTaken: "12:20",
    sessionId: "session-3",
  },
  {
    id: "hist-4",
    date: "2026-08-28T16:00:00",
    mode: "random",
    subject: "Physics",
    score: "88%",
    timeTaken: "18:45",
    sessionId: "session-4",
  },
  {
    id: "hist-5",
    date: "2026-08-27T11:20:00",
    mode: "normal",
    subject: "Chemistry",
    score: "95%",
    timeTaken: "14:10",
    sessionId: "session-5",
  },
];

export const defaultSessionTime = 600; // 10 minutes in seconds for timed mode