import {
  User,
  Exam,
  Question,
  FeatureFlag,
  PermissionMatrix,
  Subscription,
  Payment,
  SystemConfig,
  AnalyticsData,
  UserRole,
  UserStatus,
  ExamStatus,
  QuestionType,
  FeatureCategory,
  SubscriptionTier,
  PaymentStatus,
} from "./types";

// Mock Users Data
export const mockUsers: User[] = [
  {
    id: "usr_1",
    name: "Dr. Sarah Mitchell",
    email: "sarah.mitchell@university.edu",
    role: "teacher",
    status: "active",
    createdAt: "2024-01-15T08:30:00Z",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    lastActive: "2024-08-26T14:22:00Z",
    department: "Computer Science",
    teacherId: "TCH001",
  },
  {
    id: "usr_2",
    name: "Prof. James Wilson",
    email: "j.wilson@university.edu",
    role: "teacher",
    status: "active",
    createdAt: "2024-02-20T10:15:00Z",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=James",
    lastActive: "2024-08-26T16:45:00Z",
    department: "Mathematics",
    teacherId: "TCH002",
  },
  {
    id: "usr_3",
    name: "Emily Chen",
    email: "emily.chen@student.edu",
    role: "student",
    status: "active",
    createdAt: "2024-03-10T14:20:00Z",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emily",
    lastActive: "2024-08-26T18:30:00Z",
    department: "Computer Science",
    studentId: "STU2024001",
  },
  {
    id: "usr_4",
    name: "Michael Brown",
    email: "m.brown@student.edu",
    role: "student",
    status: "suspended",
    createdAt: "2024-03-15T09:45:00Z",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
    lastActive: "2024-08-20T11:00:00Z",
    department: "Mathematics",
    studentId: "STU2024002",
  },
  {
    id: "usr_5",
    name: "Lisa Anderson",
    email: "lisa.anderson@student.edu",
    role: "student",
    status: "active",
    createdAt: "2024-04-01T16:30:00Z",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa",
    lastActive: "2024-08-26T19:15:00Z",
    department: "Physics",
    studentId: "STU2024003",
  },
  {
    id: "usr_6",
    name: "Dr. Robert Taylor",
    email: "r.taylor@university.edu",
    role: "teacher",
    status: "deactivated",
    createdAt: "2023-11-20T11:00:00Z",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Robert",
    lastActive: "2024-06-15T09:30:00Z",
    department: "Physics",
    teacherId: "TCH003",
  },
  {
    id: "usr_7",
    name: "Jennifer Martinez",
    email: "j.martinez@student.edu",
    role: "student",
    status: "active",
    createdAt: "2024-04-15T13:45:00Z",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jennifer",
    lastActive: "2024-08-26T17:50:00Z",
    department: "Chemistry",
    studentId: "STU2024004",
  },
  {
    id: "usr_8",
    name: "David Kim",
    email: "d.kim@student.edu",
    role: "student",
    status: "active",
    createdAt: "2024-05-01T10:00:00Z",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=David",
    lastActive: "2024-08-26T20:00:00Z",
    department: "Computer Science",
    studentId: "STU2024005",
  },
  {
    id: "usr_9",
    name: "Amanda White",
    email: "a.white@university.edu",
    role: "teacher",
    status: "active",
    createdAt: "2024-01-05T15:30:00Z",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amanda",
    lastActive: "2024-08-26T15:20:00Z",
    department: "Chemistry",
    teacherId: "TCH004",
  },
  {
    id: "usr_10",
    name: "Chris Johnson",
    email: "c.johnson@student.edu",
    role: "student",
    status: "deactivated",
    createdAt: "2024-02-28T14:15:00Z",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Chris",
    lastActive: "2024-07-10T12:30:00Z",
    department: "Mathematics",
    studentId: "STU2024006",
  },
];

// Mock Exams Data
export const mockExams: Exam[] = [
  {
    id: "exam_1",
    title: "Data Structures Final Exam",
    subject: "Computer Science",
    createdBy: "Dr. Sarah Mitchell",
    durationMinutes: 90,
    totalMarks: 100,
    passMark: 60,
    status: "published",
    schedule: {
      startWindow: "2024-09-01T09:00:00Z",
      endWindow: "2024-09-01T11:00:00Z",
    },
    createdAt: "2024-08-15T10:00:00Z",
    updatedAt: "2024-08-20T14:30:00Z",
    questionCount: 25,
    enrolledCount: 45,
    completedCount: 38,
  },
  {
    id: "exam_2",
    title: "Calculus Midterm",
    subject: "Mathematics",
    createdBy: "Prof. James Wilson",
    durationMinutes: 120,
    totalMarks: 100,
    passMark: 50,
    status: "scheduled",
    schedule: {
      startWindow: "2024-09-05T14:00:00Z",
      endWindow: "2024-09-05T16:30:00Z",
    },
    createdAt: "2024-08-18T11:00:00Z",
    updatedAt: "2024-08-22T09:15:00Z",
    questionCount: 30,
    enrolledCount: 62,
    completedCount: 0,
  },
  {
    id: "exam_3",
    title: "Physics Fundamentals Quiz",
    subject: "Physics",
    createdBy: "Dr. Robert Taylor",
    durationMinutes: 45,
    totalMarks: 50,
    passMark: 30,
    status: "draft",
    schedule: {
      startWindow: "2024-09-10T10:00:00Z",
      endWindow: "2024-09-10T11:00:00Z",
    },
    createdAt: "2024-08-20T08:30:00Z",
    updatedAt: "2024-08-25T16:45:00Z",
    questionCount: 20,
    enrolledCount: 0,
    completedCount: 0,
  },
  {
    id: "exam_4",
    title: "Organic Chemistry Test",
    subject: "Chemistry",
    createdBy: "Amanda White",
    durationMinutes: 60,
    totalMarks: 75,
    passMark: 45,
    status: "published",
    schedule: {
      startWindow: "2024-08-28T13:00:00Z",
      endWindow: "2024-08-28T14:30:00Z",
    },
    createdAt: "2024-08-10T09:00:00Z",
    updatedAt: "2024-08-15T11:20:00Z",
    questionCount: 22,
    enrolledCount: 38,
    completedCount: 35,
  },
  {
    id: "exam_5",
    title: "Algorithms Comprehensive",
    subject: "Computer Science",
    createdBy: "Dr. Sarah Mitchell",
    durationMinutes: 150,
    totalMarks: 150,
    passMark: 90,
    status: "completed",
    schedule: {
      startWindow: "2024-08-20T09:00:00Z",
      endWindow: "2024-08-20T12:00:00Z",
    },
    createdAt: "2024-08-01T14:00:00Z",
    updatedAt: "2024-08-21T10:30:00Z",
    questionCount: 40,
    enrolledCount: 52,
    completedCount: 48,
  },
];

// Mock Questions Data
export const mockQuestions: Question[] = [
  {
    id: "q_1",
    type: "mcq",
    subject: "Computer Science",
    category: "Data Structures",
    difficulty: "medium",
    question: "What is the time complexity of binary search in a sorted array?",
    options: ["O(n)", "O(log n)", "O(n²)", "O(1)"],
    correctAnswer: "O(log n)",
    explanation: "Binary search divides the search space in half with each comparison, resulting in logarithmic time complexity.",
    tags: ["algorithms", "searching", "complexity"],
    createdBy: "Dr. Sarah Mitchell",
    createdAt: "2024-08-01T10:00:00Z",
    usageCount: 15,
  },
  {
    id: "q_2",
    type: "true_false",
    subject: "Mathematics",
    category: "Calculus",
    difficulty: "easy",
    question: "The derivative of a constant function is always zero.",
    correctAnswer: "true",
    explanation: "Since a constant function has no rate of change, its derivative is zero.",
    tags: ["calculus", "derivatives", "basics"],
    createdBy: "Prof. James Wilson",
    createdAt: "2024-08-05T14:30:00Z",
    usageCount: 22,
  },
  {
    id: "q_3",
    type: "short_answer",
    subject: "Physics",
    category: "Mechanics",
    difficulty: "hard",
    question: "Explain the concept of momentum conservation in elastic collisions.",
    correctAnswer: "In elastic collisions, both momentum and kinetic energy are conserved. The total momentum before collision equals total momentum after collision.",
    explanation: "Momentum conservation is a fundamental principle derived from Newton's laws.",
    tags: ["mechanics", "collisions", "conservation"],
    createdBy: "Dr. Robert Taylor",
    createdAt: "2024-08-10T09:15:00Z",
    usageCount: 8,
  },
  {
    id: "q_4",
    type: "mcq",
    subject: "Chemistry",
    category: "Organic Chemistry",
    difficulty: "medium",
    question: "Which functional group is present in alcohols?",
    options: ["-COOH", "-OH", "-NH2", "-CHO"],
    correctAnswer: "-OH",
    explanation: "Alcohols contain the hydroxyl (-OH) functional group bonded to a carbon atom.",
    tags: ["organic", "functional groups", "alcohols"],
    createdBy: "Amanda White",
    createdAt: "2024-08-12T11:00:00Z",
    usageCount: 18,
  },
  {
    id: "q_5",
    type: "mcq",
    subject: "Computer Science",
    category: "Algorithms",
    difficulty: "hard",
    question: "Which sorting algorithm has the best average-case time complexity?",
    options: ["Bubble Sort", "Quick Sort", "Selection Sort", "Insertion Sort"],
    correctAnswer: "Quick Sort",
    explanation: "Quick Sort has O(n log n) average-case time complexity, making it efficient for large datasets.",
    tags: ["algorithms", "sorting", "complexity"],
    createdBy: "Dr. Sarah Mitchell",
    createdAt: "2024-08-15T08:45:00Z",
    usageCount: 12,
  },
];

// Mock Feature Flags
export const mockFeatureFlags: FeatureFlag[] = [
  {
    id: "ff_1",
    key: "ai_question_generation",
    name: "AI Question Generation",
    description: "Enable AI-powered question generation for teachers",
    enabled: true,
    category: "ai",
    lastModified: "2024-08-20T10:00:00Z",
    modifiedBy: "admin",
  },
  {
    id: "ff_2",
    key: "live_proctoring",
    name: "Live Proctoring",
    description: "Real-time monitoring and proctoring during exams",
    enabled: true,
    category: "security",
    lastModified: "2024-08-18T14:30:00Z",
    modifiedBy: "admin",
  },
  {
    id: "ff_3",
    key: "maintenance_mode",
    name: "Maintenance Mode",
    description: "Put the platform in maintenance mode for updates",
    enabled: false,
    category: "system",
    lastModified: "2024-08-15T09:00:00Z",
    modifiedBy: "admin",
  },
  {
    id: "ff_4",
    key: "auto_grading_essays",
    name: "Auto-Grading Essays",
    description: "AI-assisted grading for descriptive answers",
    enabled: true,
    category: "ai",
    lastModified: "2024-08-22T11:15:00Z",
    modifiedBy: "admin",
  },
  {
    id: "ff_5",
    key: "session_recording",
    name: "Session Recording",
    description: "Record exam sessions for security review",
    enabled: false,
    category: "security",
    lastModified: "2024-08-10T16:45:00Z",
    modifiedBy: "admin",
  },
  {
    id: "ff_6",
    key: "bulk_user_import",
    name: "Bulk User Import",
    description: "Enable CSV-based bulk user import functionality",
    enabled: true,
    category: "system",
    lastModified: "2024-08-25T08:30:00Z",
    modifiedBy: "admin",
  },
];

// Mock Permission Matrix
export const mockPermissionMatrix: PermissionMatrix[] = [
  {
    role: "Super Admin",
    permissions: {
      users: { read: true, write: true, delete: true, admin: true },
      exams: { read: true, write: true, delete: true, admin: true },
      questions: { read: true, write: true, delete: true, admin: true },
      analytics: { read: true, write: true, delete: false, admin: true },
      settings: { read: true, write: true, delete: false, admin: true },
      features: { read: true, write: true, delete: false, admin: true },
    },
  },
  {
    role: "Exam Manager",
    permissions: {
      users: { read: true, write: false, delete: false, admin: false },
      exams: { read: true, write: true, delete: true, admin: false },
      questions: { read: true, write: true, delete: true, admin: false },
      analytics: { read: true, write: false, delete: false, admin: false },
      settings: { read: true, write: false, delete: false, admin: false },
      features: { read: true, write: false, delete: false, admin: false },
    },
  },
  {
    role: "Support Lead",
    permissions: {
      users: { read: true, write: true, delete: false, admin: false },
      exams: { read: true, write: false, delete: false, admin: false },
      questions: { read: false, write: false, delete: false, admin: false },
      analytics: { read: true, write: false, delete: false, admin: false },
      settings: { read: true, write: false, delete: false, admin: false },
      features: { read: true, write: false, delete: false, admin: false },
    },
  },
];

// Mock Subscriptions
export const mockSubscriptions: Subscription[] = [
  {
    id: "sub_1",
    userId: "usr_3",
    userName: "Emily Chen",
    userEmail: "emily.chen@student.edu",
    tier: "pro",
    status: "active",
    startDate: "2024-03-10T00:00:00Z",
    endDate: "2025-03-10T00:00:00Z",
    autoRenew: true,
    amount: 99.99,
    currency: "USD",
  },
  {
    id: "sub_2",
    userId: "usr_5",
    userName: "Lisa Anderson",
    userEmail: "lisa.anderson@student.edu",
    tier: "institutional",
    status: "active",
    startDate: "2024-04-01T00:00:00Z",
    endDate: "2025-04-01T00:00:00Z",
    autoRenew: true,
    amount: 499.99,
    currency: "USD",
  },
  {
    id: "sub_3",
    userId: "usr_7",
    userName: "Jennifer Martinez",
    userEmail: "j.martinez@student.edu",
    tier: "free",
    status: "active",
    startDate: "2024-04-15T00:00:00Z",
    endDate: "2025-04-15T00:00:00Z",
    autoRenew: false,
    amount: 0,
    currency: "USD",
  },
  {
    id: "sub_4",
    userId: "usr_8",
    userName: "David Kim",
    userEmail: "d.kim@student.edu",
    tier: "pro",
    status: "expired",
    startDate: "2024-05-01T00:00:00Z",
    endDate: "2024-08-01T00:00:00Z",
    autoRenew: false,
    amount: 99.99,
    currency: "USD",
  },
];

// Mock Payments
export const mockPayments: Payment[] = [
  {
    id: "pay_1",
    subscriptionId: "sub_1",
    userId: "usr_3",
    userName: "Emily Chen",
    amount: 99.99,
    currency: "USD",
    status: "success",
    paymentMethod: "Credit Card",
    transactionId: "TXN_20240310_001",
    invoiceUrl: "/invoices/inv_001.pdf",
    createdAt: "2024-03-10T10:30:00Z",
    processedAt: "2024-03-10T10:31:00Z",
  },
  {
    id: "pay_2",
    subscriptionId: "sub_2",
    userId: "usr_5",
    userName: "Lisa Anderson",
    amount: 499.99,
    currency: "USD",
    status: "success",
    paymentMethod: "Bank Transfer",
    transactionId: "TXN_20240401_002",
    invoiceUrl: "/invoices/inv_002.pdf",
    createdAt: "2024-04-01T14:00:00Z",
    processedAt: "2024-04-01T14:05:00Z",
  },
  {
    id: "pay_3",
    subscriptionId: "sub_4",
    userId: "usr_8",
    userName: "David Kim",
    amount: 99.99,
    currency: "USD",
    status: "failed",
    paymentMethod: "Credit Card",
    transactionId: "TXN_20240501_003",
    invoiceUrl: "/invoices/inv_003.pdf",
    createdAt: "2024-05-01T09:00:00Z",
  },
  {
    id: "pay_4",
    subscriptionId: "sub_1",
    userId: "usr_3",
    userName: "Emily Chen",
    amount: 99.99,
    currency: "USD",
    status: "pending",
    paymentMethod: "Credit Card",
    transactionId: "TXN_20240826_004",
    createdAt: "2024-08-26T16:00:00Z",
  },
];

// Mock System Config
export const mockSystemConfig: SystemConfig[] = [
  {
    id: "cfg_1",
    key: "app_name",
    value: "Testify",
    type: "string",
    category: "general",
    description: "Application name displayed in UI",
    updatedAt: "2024-08-01T10:00:00Z",
    updatedBy: "admin",
  },
  {
    id: "cfg_2",
    key: "session_timeout",
    value: "3600",
    type: "number",
    category: "security",
    description: "Session timeout in seconds",
    updatedAt: "2024-08-15T14:30:00Z",
    updatedBy: "admin",
  },
  {
    id: "cfg_3",
    key: "smtp_host",
    value: "smtp.gmail.com",
    type: "string",
    category: "email",
    description: "SMTP server hostname",
    updatedAt: "2024-08-10T09:00:00Z",
    updatedBy: "admin",
  },
  {
    id: "cfg_4",
    key: "max_retry_attempts",
    value: "3",
    type: "number",
    category: "limits",
    description: "Maximum retry attempts for failed operations",
    updatedAt: "2024-08-20T11:15:00Z",
    updatedBy: "admin",
  },
  {
    id: "cfg_5",
    key: "maintenance_message",
    value: "System under maintenance. Please try again later.",
    type: "string",
    category: "general",
    description: "Message displayed during maintenance mode",
    updatedAt: "2024-08-05T16:45:00Z",
    updatedBy: "admin",
  },
];

// Mock Analytics Data
export const mockAnalyticsData: AnalyticsData = {
  systemHealth: [
    {
      timestamp: "2024-08-26T00:00:00Z",
      cpuUsage: 45,
      memoryUsage: 62,
      diskUsage: 58,
      apiLatency: 120,
      activeConnections: 1250,
    },
    {
      timestamp: "2024-08-26T04:00:00Z",
      cpuUsage: 38,
      memoryUsage: 58,
      diskUsage: 58,
      apiLatency: 95,
      activeConnections: 890,
    },
    {
      timestamp: "2024-08-26T08:00:00Z",
      cpuUsage: 72,
      memoryUsage: 75,
      diskUsage: 59,
      apiLatency: 180,
      activeConnections: 2100,
    },
    {
      timestamp: "2024-08-26T12:00:00Z",
      cpuUsage: 68,
      memoryUsage: 71,
      diskUsage: 59,
      apiLatency: 155,
      activeConnections: 1950,
    },
    {
      timestamp: "2024-08-26T16:00:00Z",
      cpuUsage: 55,
      memoryUsage: 65,
      diskUsage: 59,
      apiLatency: 130,
      activeConnections: 1680,
    },
    {
      timestamp: "2024-08-26T20:00:00Z",
      cpuUsage: 42,
      memoryUsage: 60,
      diskUsage: 58,
      apiLatency: 110,
      activeConnections: 1420,
    },
  ],
  examStats: {
    totalExams: 156,
    publishedExams: 89,
    scheduledExams: 34,
    draftExams: 22,
    completedExams: 11,
    passRate: 78.5,
    averageScore: 73.2,
    completionRate: 85.3,
  },
  userStats: {
    totalUsers: 1248,
    activeUsers: 892,
    newUsers: 156,
    dailyActiveUsers: [
      { date: "2024-08-20", count: 720 },
      { date: "2024-08-21", count: 780 },
      { date: "2024-08-22", count: 810 },
      { date: "2024-08-23", count: 795 },
      { date: "2024-08-24", count: 850 },
      { date: "2024-08-25", count: 820 },
      { date: "2024-08-26", count: 892 },
    ],
    retentionRate: 82.5,
    averageSessionDuration: 45,
  },
  examPerformance: [
    {
      subject: "Computer Science",
      passCount: 245,
      failCount: 35,
      averageScore: 78.5,
    },
    {
      subject: "Mathematics",
      passCount: 198,
      failCount: 42,
      averageScore: 74.2,
    },
    {
      subject: "Physics",
      passCount: 156,
      failCount: 28,
      averageScore: 76.8,
    },
    {
      subject: "Chemistry",
      passCount: 134,
      failCount: 22,
      averageScore: 79.1,
    },
    {
      subject: "Biology",
      passCount: 112,
      failCount: 18,
      averageScore: 80.3,
    },
  ],
};